# Generated by Django 3.2.12 on 2022-03-12 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
        ('bot_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_messages.city'),
        ),
    ]
