# Generated by Django 3.2.12 on 2022-02-27 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0012_alter_message_actions'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_messages.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_lang',
            field=models.CharField(blank=True, choices=[('ru', 'Русский'), ('kk', 'Казахский')], max_length=3),
        ),
    ]
