# Generated by Django 3.2.12 on 2022-03-12 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.IntegerField(blank=True, choices=[(0, 'Ораза кестесі'), (1, 'Қадір түні'), (2, 'Дұғалар'), (3, 'Сұрақ жауап (FAQ)'), (4, 'Ұсыныс, сын'), (5, 'Чатқа қосылу'), (6, 'Рамазан жоспары'), (7, 'Оқылу керек дұғалар'), (8, 'Сұрақ-жауап (қадір туні)'), (9, 'Қадір түні жайында'), (10, 'Қадір түнінде 10 сауапты іс'), (11, 'Қадір түнінде 10 күнәлі іс'), (12, 'Істелуі тиіс ең таңдаулы амалдар'), (13, 'Артқа')], verbose_name='Комманда')),
                ('name_kk', models.CharField(blank=True, max_length=100, verbose_name='Название комманды (каз)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Название комманды (рус)')),
                ('link', models.CharField(blank=True, max_length=5000, verbose_name='Ссылка (если комманда link)')),
            ],
            options={
                'verbose_name': 'Действия',
                'verbose_name_plural': 'Действия',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kk', models.CharField(blank=True, max_length=100, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Название (рус)')),
                ('type', models.IntegerField(choices=[(0, 'Регион'), (1, 'Город')], default=0)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_kk', models.CharField(max_length=255, verbose_name='Название категории (каз)')),
                ('category_ru', models.CharField(max_length=255, verbose_name='Название категории (рус)')),
            ],
            options={
                'verbose_name': 'Категория вопроса',
                'verbose_name_plural': 'Категория вопросов',
            },
        ),
        migrations.CreateModel(
            name='Pray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус)')),
                ('link', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на источник')),
                ('pray_type', models.IntegerField(choices=[(0, 'Дұға'), (1, 'Кадір түні')], default=0, verbose_name='Тип')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_messages.action')),
            ],
            options={
                'verbose_name': 'Молитва',
                'verbose_name_plural': 'Молитвы',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_kk', models.TextField(max_length=4096, null=True, verbose_name='текст (каз)')),
                ('text_ru', models.TextField(max_length=4096, null=True, verbose_name='текст (рус)')),
                ('pray', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text', to='bot_messages.pray')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='schedules', verbose_name='Фото расписания')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='Текст')),
                ('link', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на источник')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_messages.city')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Усыныс')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
            options={
                'verbose_name': 'Запрос пользователя',
                'verbose_name_plural': 'Запросы пользователей',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_kk', models.TextField(blank=True, max_length=1000, verbose_name='Сообщение (каз)')),
                ('message_ru', models.TextField(blank=True, max_length=1000, verbose_name='Сообщение (рус)')),
                ('type', models.PositiveIntegerField(choices=[(0, 'Не выбрано'), (1, 'Стартовое сообщение'), (2, 'Меню'), (3, 'Выбор города'), (4, 'Қадір түні'), (5, 'Дұғалар'), (6, 'Рамазан жоспары'), (7, 'Рамазан жайлы сұрақтар'), (8, 'Ұсыныс')], default=0, verbose_name='Тип сообщения')),
                ('inline_count', models.PositiveIntegerField(choices=[(1, '1 кнопка'), (2, '2 кнопки')], default=1, verbose_name='Количество кнопок в одной линии')),
                ('actions', models.ManyToManyField(blank=True, to='bot_messages.Action')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщение',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_kk', models.CharField(max_length=255, verbose_name='Вопрос (каз)')),
                ('question_ru', models.CharField(max_length=255, verbose_name='Вопрос (рус)')),
                ('body_kk', models.TextField(blank=True, max_length=4096, verbose_name='Ответ (каз)')),
                ('body_ru', models.TextField(blank=True, max_length=4096, verbose_name='Ответ (рус)')),
                ('link', models.CharField(blank=True, max_length=4096, verbose_name='Ссылка на источник')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_messages.faqcategory')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопрос-ответ',
            },
        ),
    ]
