# Generated by Django 3.2.12 on 2022-02-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_kk', models.TextField(max_length=1000, verbose_name='Сообщение (каз)')),
                ('message_ru', models.TextField(max_length=1000, verbose_name='Сообщение (рус)')),
                ('type', models.PositiveIntegerField(choices=[(0, 'Не выбрано'), (1, 'Стартовое сообщение'), (2, 'Меню')], default=0)),
            ],
        ),
    ]
