# Generated by Django 3.2.12 on 2022-02-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(blank=True, choices=[('shedule', 'Ораза кестесі')], max_length=100, verbose_name='комманда')),
                ('name_kk', models.TextField(blank=True, max_length=100, verbose_name='Название комманды (каз)')),
                ('name_ru', models.TextField(blank=True, max_length=100, verbose_name='Название комманды (рус)')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='message_kk',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Сообщение (каз)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_ru',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Сообщение (рус)'),
        ),
        migrations.AddField(
            model_name='message',
            name='actions',
            field=models.ManyToManyField(to='bot_messages.Action'),
        ),
    ]
