# Generated by Django 3.2.12 on 2022-03-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='message',
            name='inline_count',
            field=models.PositiveIntegerField(choices=[(1, '1 кнопка'), (2, '2 кнопки'), (3, '3 кнопки'), (4, '4 кнопки')], default=1, verbose_name='Количество кнопок в одной линии'),
        ),
    ]
