# Generated by Django 3.2.12 on 2022-02-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0002_auto_20220223_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kk', models.CharField(blank=True, max_length=100, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Название (рус)')),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='name_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название комманды (каз)'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название комманды (рус)'),
        ),
    ]
