# Generated by Django 3.2.12 on 2022-03-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0002_auto_20220313_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='link',
        ),
    ]
