# Generated by Django 3.2.12 on 2022-02-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0003_auto_20220223_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='link',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Ссылка (если комманда link)'),
        ),
        migrations.AlterField(
            model_name='action',
            name='command',
            field=models.IntegerField(blank=True, choices=[(0, 'Ораза кестесі'), (1, 'Қадір түні'), (2, 'Дұғалар'), (3, 'Сұрақ жауап (FAQ)'), (4, 'Ұсыныс, сын'), (5, 'Чатқа қосылу'), (6, 'Рамазан жоспары'), (7, 'Оқылу керек дұғалар'), (8, 'Қадір түні жайында'), (9, 'Қадір түнінде 10 сауапты іс'), (10, 'Істелуі тиіс ең таңдаулы амалдар'), (11, 'Артқа')], verbose_name='Комманда'),
        ),
    ]
