# Generated by Django 3.2.12 on 2022-02-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0004_auto_20220223_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='type',
            field=models.IntegerField(choices=[(0, 'Регион'), (1, 'Город')], default=0),
        ),
    ]
