# Generated by Django 3.2.12 on 2022-02-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0005_city_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_kk', models.CharField(max_length=255, verbose_name='Вопрос (каз)')),
                ('question_ru', models.CharField(max_length=255, verbose_name='Вопрос (рус)')),
                ('body_kk', models.TextField(blank=True, max_length=1000, verbose_name='Ответ комманды (каз)')),
                ('body_ru', models.TextField(blank=True, max_length=1000, verbose_name='Название комманды (рус)')),
                ('link', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на источник')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Усыныс')),
            ],
        ),
    ]
