# Generated by Django 3.2.12 on 2022-02-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0006_faq_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Действия', 'verbose_name_plural': 'Действия'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Город'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос-ответ', 'verbose_name_plural': 'Вопрос-ответ'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщение'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Запросы пользователей', 'verbose_name_plural': 'Запросы пользователей'},
        ),
    ]
