# Generated by Django 3.2.12 on 2022-02-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0007_auto_20220225_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.IntegerField(choices=[(0, 'обычный'), (1, 'Молитва'), (2, 'Кадір түні')], default=0, verbose_name='Тип ответа'),
        ),
        migrations.AddField(
            model_name='message',
            name='inline_count',
            field=models.PositiveIntegerField(choices=[], default=1, verbose_name='Количество кнопок в одной линии'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='body_kk',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Ответ (каз)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='body_ru',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Ответ (рус)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Не выбрано'), (1, 'Стартовое сообщение'), (2, 'Меню')], default=0, verbose_name='Тип сообщения'),
        ),
    ]
