# Generated by Django 3.2.12 on 2022-02-26 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0008_auto_20220226_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус)')),
                ('text_kk', models.TextField(blank=True, verbose_name='Текст (каз)')),
                ('text_ru', models.TextField(blank=True, verbose_name='Текст (рус)')),
                ('link', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на источник')),
                ('pray_type', models.IntegerField(choices=[(0, 'Дұға'), (1, 'Кадір түні')], default=0, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Молитва',
                'verbose_name_plural': 'Молитвы',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='schedules', verbose_name='Фото расписания')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='Текст')),
                ('link', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на источник')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_messages.city')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
