# Generated by Django 3.2.12 on 2022-02-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0009_pray_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='inline_count',
            field=models.PositiveIntegerField(choices=[(1, '1 кнопка'), (2, '2 кнопки')], default=1, verbose_name='Количество кнопок в одной линии'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Не выбрано'), (1, 'Стартовое сообщение'), (2, 'Меню'), (3, 'Выбор города'), (4, 'Қадір түні'), (5, 'Дұғалар'), (6, 'Рамазан жайлы сұрақтар'), (7, 'Ұсыныс')], default=0, verbose_name='Тип сообщения'),
        ),
    ]
