# Generated by Django 3.2.12 on 2022-02-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0010_auto_20220227_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Не выбрано'), (1, 'Стартовое сообщение'), (2, 'Меню'), (3, 'Выбор города'), (4, 'Қадір түні'), (5, 'Дұғалар'), (6, 'Рамазан жоспары'), (7, 'Рамазан жайлы сұрақтар'), (8, 'Ұсыныс')], default=0, verbose_name='Тип сообщения'),
        ),
    ]
