# Generated by Django 3.2.12 on 2022-02-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0011_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='actions',
            field=models.ManyToManyField(blank=True, to='bot_messages.Action'),
        ),
    ]
