# Generated by Django 3.2.12 on 2022-02-28 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0013_auto_20220301_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_kk', models.TextField(max_length=4096, null=True, verbose_name='текст (каз)')),
                ('text_ru', models.TextField(max_length=4096, null=True, verbose_name='текст (рус)')),
                ('pray', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text', to='bot_messages.pray')),
            ],
        ),
    ]
